FinalProgram-9/Models/Question.cs
namespace FinalProgram_9.Models
{
    public class Question
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public DateTime DateOfCreate { get; set; }
        public DateTime? DateOfClose { get; set; }
        public int UpVote { get; set; }
        public int DownVote { get; set; }



        public string? UserId { get; set; } 
        public virtual ApplicationUser? User { get; set; }
        public virtual ICollection<QuestionTag> QuestionTags { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public Question(string title, string body, string userId)
        {
            this.Title = title;
            this.Body = body;
            this.UserId = userId;
            this.DateOfCreate = DateTime.Now;

            QuestionTags = new HashSet<QuestionTag>();
            Answers = new HashSet<Answer>();
            Comments = new HashSet<Comment>();
        }
        public Question()
        {
            QuestionTags = new HashSet<QuestionTag>();
            Answers = new HashSet<Answer>();
            Comments = new HashSet<Comment>();
        }
    }
}

FinalProgram-9/Controllers/CommentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProgram_9.Data;
using FinalProgram_9.Models;

namespace FinalProgram_9.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CommentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Comments.Include(c => c.Answer).Include(c => c.Question).Include(c => c.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Answer)
                .Include(c => c.Question)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public IActionResult Create(int questionId, int answerId)
        {
            if(answerId == 0)
            {
                ViewBag.questionId=questionId;
            }
            if(answerId!= 0)
            {
                ViewBag.answerId=answerId;
                ViewBag.questionId = questionId;
            }
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int questionId, int answerId, string comment)
        {
           if(questionId != 0)
            {
                var username = User.Identity.Name;
                var userId = _context.Users.First(u => u.UserName == username).Id;
                Comment questionComment = new Comment(userId,questionId,comment);
                _context.Comments.Add(questionComment);
                _context.SaveChanges();
            }

            if (answerId != 0)
            {
                var username = User.Identity.Name;
                var userId = _context.Users.First(u => u.UserName == username).Id;
                Comment answerComment = new Comment(userId, answerId,questionId, comment);
                _context.Comments.Add(answerComment);
                _context.SaveChanges();
            }

            return RedirectToAction("Details","Questions", new {id=questionId});
        }



        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["AnswerId"] = new SelectList(_context.Answers, "Id", "Id", comment.AnswerId);
            ViewData["QuestionId"] = new SelectList(_context.Questions, "Id", "Id", comment.QuestionId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", comment.UserId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ContentOfComment,UserId,QuestionId,AnswerId")] Comment comment)
        {
            if (id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AnswerId"] = new SelectList(_context.Answers, "Id", "Id", comment.AnswerId);
            ViewData["QuestionId"] = new SelectList(_context.Questions, "Id", "Id", comment.QuestionId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", comment.UserId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Answer)
                .Include(c => c.Question)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _context.Comments.FindAsync(id);
            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(int id)
        {
            return _context.Comments.Any(e => e.Id == id);
        }
    }
}

FinalProgram-9/Controllers/QuestionsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProgram_9.Data;
using FinalProgram_9.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace FinalProgram_9.Controllers
{
    [Authorize]
    public class QuestionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public QuestionsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Questions

        public async Task<IActionResult> Index(string OrderingQ)
        {
            if (OrderingQ != null)
            {
                if (OrderingQ == "Active")
                {
                    var mostActiveQuestions = _context.Questions.Include(q => q.User).Include(q => q.Answers).OrderByDescending(q => q.Answers.Count).ToList();
                    return View(mostActiveQuestions);
                }
                else
                {
                    var mostActiveQuestions = _context.Questions.Include(q => q.User).Include(q => q.Answers).OrderByDescending(q => q.DateOfCreate).ToList();
                    return View(mostActiveQuestions);
                }
            }
            var applicationDbContext = _context.Questions.Include(q => q.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Questions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions.Include(q=>q.Answers).ThenInclude(a=>a.Comments).Include(q=>q.Comments)
                .Include(q => q.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        // GET: Questions/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            SelectList tagList = new SelectList(_context.Tags, "Id", "Name");
            ViewBag.TagList = tagList;
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Body,DateOfCreate,DateOfClose,UpVote,DownVote,UserId")] Question question, int tagId)
        {
            if (ModelState.IsValid)
            {
                _context.Add(question);
                QuestionTag qt = new QuestionTag(question.Id, tagId);
                question.QuestionTags.Add(qt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", question.UserId);
         
  
           
            return View(question);
        }
        


        // GET: Questions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions.FindAsync(id);
            if (question == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", question.UserId);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Body,DateOfCreate,DateOfClose,UpVote,DownVote,UserId")] Question question)
        {
            if (id != question.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(question);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionExists(question.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", question.UserId);
            return View(question);
        }

        // GET: Questions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var question = await _context.Questions
                .Include(q => q.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }


        [HttpPost]
        public async Task<IActionResult>CreateAnswer(string AnswerContent, int questionId)
        {
            var UserName = User.Identity.Name;
            var LogedUser = _context.Users.First(u => u.UserName == UserName);
            var UserId = LogedUser.Id;

            var newAnswer = new Answer();
            newAnswer.AnswerContent=AnswerContent;
            newAnswer.QuestionId=questionId;
            _context.Answers.Add(newAnswer);
            _context.SaveChanges();
            return RedirectToAction("Details",new { id = questionId });

        }


        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var question = await _context.Questions.FindAsync(id);
            _context.Questions.Remove(question);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool QuestionExists(int id)
        {
            return _context.Questions.Any(e => e.Id == id);
        }
    }
}

FinalProgram-9/Views/Questions/Create.cshtml
@model FinalProgram_9.Models.Question

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfCreate" class="control-label"></label>
                <input asp-for="DateOfCreate" class="form-control" />
                <span asp-validation-for="DateOfCreate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfClose" class="control-label"></label>
                <input asp-for="DateOfClose" class="form-control" />
                <span asp-validation-for="DateOfClose" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpVote" class="control-label"></label>
                <input asp-for="UpVote" class="form-control" />
                <span asp-validation-for="UpVote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DownVote" class="control-label"></label>
                <input asp-for="DownVote" class="form-control" />
                <span asp-validation-for="DownVote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <select name = "tagId" asp-items="@ViewBag.TagList"></select>
         

     


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProgram-9/Views/Questions/Delete.cshtml
@model FinalProgram_9.Models.Question

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfCreate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfCreate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfClose)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfClose)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpVote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpVote)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DownVote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DownVote)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FinalProgram-9/Views/Questions/Details.cshtml
@model FinalProgram_9.Models.Question

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfCreate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfCreate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfClose)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfClose)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpVote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpVote)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DownVote)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DownVote)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<ul>
    <p> Comments</p>
@foreach(var comment in Model.Comments)
{
    <li>@comment.ContentOfComment</li>
    <li>@comment.UserId</li>
}
</ul>
<a asp-controller="Comments" asp-action="Create" asp-route-questionId=@Model.Id>
    add question comment
</a>


<div>
    <h4>Answers</h4>
    <ul>
    @foreach(var Answer in Model.Answers)
    {
        <li>@Answer.AnswerContent</li>
        <li>Answer.Id</li>
        <a asp-controller="Comments" asp-action="Create" asp-route-questionId=@Model.Id asp-route-answerid=@Answer.Id>
    add answer comment
</a>
    }
    </ul>
</div>


<form asp-action="CreateAnswer" method="post" asp-route-questionId=@Model.Id>

    <textarea cols="100" rows="9" name="AnswerContent"></textarea>
    <button type="submit">Confirm</button>
</form>


@*<div>
@if(Model.QuestionTags != null)
{
foreach (var questionTag in Model.QuestionTags)
{
<a asp-action="ShowAllQuestionsByTag" asp-route-tagId="@questionTag.TagId">@questionTag.Tag.Name</a>
}
}
</div>

@{
ViewData["Title"] = "ShowAllQuestionsByTag";
}



<h1>ShowAllQuestionsByTag</h1>



<p>
<a asp-action="Create">Create New</a>
</p>
<table class="table">
<thead>
<tr>
<th>
@Html.DisplayNameFor(model => model.QuestionTags)
</th>
<th>
@Html.DisplayNameFor(model => model.QuestionTags)
</th>
<th></th>
</tr>
</thead>
<tbody>*@
@*@foreach (var item in Model) {
<tr>
<td>
@Html.DisplayFor(modelItem => item.Tag.Name)
</td>
<td>
@Html.DisplayFor(modelItem => item.Question.Title)
</td>
<td>
<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
<a asp-action="QuestionDetails" asp-route-questionId="@item.QuestionId">Details</a> |
<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
</td>
</tr>
}*@
</tbody>
</table>

FinalProgram-9/Views/Questions/Edit.cshtml
@model FinalProgram_9.Models.Question

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfCreate" class="control-label"></label>
                <input asp-for="DateOfCreate" class="form-control" />
                <span asp-validation-for="DateOfCreate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfClose" class="control-label"></label>
                <input asp-for="DateOfClose" class="form-control" />
                <span asp-validation-for="DateOfClose" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpVote" class="control-label"></label>
                <input asp-for="UpVote" class="form-control" />
                <span asp-validation-for="UpVote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DownVote" class="control-label"></label>
                <input asp-for="DownVote" class="form-control" />
                <span asp-validation-for="DownVote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FinalProgram-9/Views/Questions/Index.cshtml
@model IEnumerable<FinalProgram_9.Models.Question>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New Questions</a>
    <a asp-action="Index" asp-route-OrderingQ="The Newest">The Newest Questions</a>
    <a asp-action="Index" asp-route-OrderingQ="Active">The Most Active Questions</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfCreate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfClose)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpVote)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DownVote)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfCreate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfClose)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpVote)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DownVote)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>